Update user guides instructions
nephio-project/docs pull request #102
Opened 2024-02-01 18:47 UTC by electrocucaracha

This PR fixes some instructions describe in the Free5GC and OAI user guides, removes some trail spaces, and simplifies the get logs instructions.

2024-02-01 19:03 UTC, rravindran123 commented
When I tested yesterday, the UPF was stuck in the Init stage, @arora-sagar mentioned the documentation didnt cover the step to include the MetalLb ip-address pool configuration. Hope that is taken care off in this PR, haven't validated the testing against this updated instructions yet.

2024-02-01 21:43 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +To list the networks you can use the below command
It might take a couple of seconds for the networks to come up. To list the networks you can use the below command

2024-02-01 22:02 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +Within five minutes of applying the RAN and Core Operator YAML file, you should see `oai-core` and `oai-cn-operators` namespaces on core workload cluster, :
Within five minutes of applying the RAN, Core Operator, and database Packages, you should see `oai-core` and `oai-cn-operators` namespaces on the Core workload cluster,

2024-02-01 22:05 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
>  ```
Can you replace the output here? Now it is packagevariant rather than a set 

```
packagevariantset.config.porch.kpt.dev/oai-nrf created
packagevariantset.config.porch.kpt.dev/oai-udm created
packagevariantset.config.porch.kpt.dev/oai-udr created
packagevariantset.config.porch.kpt.dev/oai-ausf created
packagevariantset.config.porch.kpt.dev/oai-amf created
packagevariantset.config.porch.kpt.dev/oai-smf created
packagevariant.config.porch.kpt.dev/oai-upf-edge created
```

2024-02-01 22:07 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +All the NFs will wait for NRF to come up and then they will register to NRF. SMF has a dependency on UPF which is described by [`dependency.yaml` file](https://github.com/OPENAIRINTERFACE/oai-package
Just as a remark can you change the r2 in the link with `v2.0.0` I will create it at OAI side.

2024-02-01 22:35 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +All the NFs will wait for NRF to come up and then they will register to NRF. SMF has a dependency on UPF which is described by [`dependency.yaml` file](https://github.com/OPENAIRINTERFACE/oai-package
Can you change it to around ~26 mins

2024-02-01 23:07 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
Can you update it to ~20 mins instead?

2024-02-01 23:12 UTC, arora-sagar commented
I just did the testing and the comments are based on that testing for metal lb. I have to do another PR and add a section after networking to run the script `./test-infra/e2e/tests/oai/001-metalb.sh` in test-infra I will detach it from `001-infra.sh` and make it a sub test of `001` test.

2024-02-01 23:31 UTC, arora-sagar commented
I did the PR here for metal-lb issue --> https://github.com/nephio-project/test-infra/pull/235

2024-02-02 12:27 UTC, CsatariGergely requested changes

2024-02-02 12:27 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +All the NFs will wait for NRF to come up and then they will register to NRF. SMF has a dependency on UPF which is described by [`dependency.yaml` file](https://github.com/OPENAIRINTERFACE/oai-package
The link provided is incorrect.

2024-02-02 15:27 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +All the NFs will wait for NRF to come up and then they will register to NRF. SMF has a dependency on UPF which is described by [`dependency.yaml` file](https://github.com/OPENAIRINTERFACE/oai-package
@CsatariGergely that is on OAI side. I will make that link once R2 tags are available.

2024-02-02 17:41 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +All the NFs will wait for NRF to come up and then they will register to NRF. SMF has a dependency on UPF which is described by [`dependency.yaml` file](https://github.com/OPENAIRINTERFACE/oai-package
Ok, I just removed the reference for now. I'll include later once the tag is created

2024-02-03 15:51 UTC, liamfallon commented
/approve
/lgtm

2024-02-03 15:51 UTC, merged