Adding Helm-To-Operator-Codegen-Sdk Documentation
nephio-project/docs pull request #117
Opened 2024-02-22 06:45 UTC by jain-ashish-sam

The current pr contains the user-guide as well as developer-guide for helm-to-operator-codegen-sdk which is a part of nephio sdk (https://github.com/nephio-project/nephio-sdk)

2024-02-22 10:41 UTC, efiacor commented
/retest

2024-02-22 17:56 UTC, electrocucaracha reviewed
Initial review

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/_index.md
> +* [Using Helm To Operator Codegen Sdk](/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md)
I think that relative paths can work here
```suggestion
* [Using Helm To Operator Codegen Sdk](helm-to-operator-codegen-sdk-user-guide.md)
```

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +In a nutshell, Firstly, the Helm-Charts are converted to Yamls using the values provided in "values.yaml". Then, each Kubernetes Resource Manifest (KRM) in the YAML is translated into Go code, employ
https://cloud.google.com/blog/topics/developers-practitioners/build-platform-krm-part-2-how-kubernetes-resource-model-works
```suggestion
In a nutshell, the Helm-Charts are converted to YAML files using the values provided in "values.yaml". Then, each Kubernetes Resource Model (KRM) in the YAML is translated into Go code, employing one of two methods.
```

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +After the conversion process, all the generated Go code is gathered and compiled into a single Go file. This resulting file contains functions that can be readily utilized by Kubernetes operators.
```suggestion
After the conversion process, all the generated Go code is gathered and compiled into a single Go file. This process results in a file that contains functions which can be readily utilized by Kubernetes operators.
```

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +Helm to Yaml conversion is achieved by running the command
```suggestion
### Flow-1: Helm to YAML
Helm to YAML conversion is achieved by running the following command
```

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +`helm template <chart>  --namespace <namespace>  --output-dir “temp/templated/”` Internally. As of now, It retrieves the values from default "values.yaml"
```suggestion
`helm template <chart>  --namespace <namespace>  --output-dir “temp/templated/”` Internally. As of now, it retrieves the values from default "values.yaml"
```

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +### Flow-2: Yaml Split
```suggestion
### Flow-2: YAML Split
```

2024-02-22 17:56 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +The SDK iterates over each YAML file in the "converted-yamls" directory. If a YAML file contains multiple Kubernetes Resource Manifests (KRM), separated by "---", the SDK splits the YAML file accordi
```suggestion
The SDK iterates over each YAML file in the "converted-yamls" directory. If a YAML file contains multiple Kubernetes Resource Models (KRMs), separated by "---", the SDK splits the YAML file accordingly to isolate each individual KRM resource. This ensures that each KRM resource is processed independently.
```

2024-02-23 09:45 UTC, lapentad commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +4. A Kubernetes Cluster with Calico CNI and multus-cni plugin (Can Refer [here](https://medium.com/rahasak/deploying-5g-core-network-with-free5gc-kubernets-and-helm-charts-29741cea3922), Before "Depl
Hi when using free5gc I always found it easier to work with [Flannel for this reason ](https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/docs/demo/Setup-free5gc-and-test-with-UERANSIM.md#tun-interface-correctly-created-on-the-ue-but-internet)

> ipv4.ip_forward We remind you that some CNI plugins (e.g. [Flannel](https://github.com/flannel-io/flannel)) allow this functionality by default, while others (.e.g. [Calico](https://github.com/projectcalico/cni-plugin)) require a [special configuration](https://docs.projectcalico.org/reference/host-endpoints/forwarded).

2024-02-23 09:59 UTC, lapentad commented
I think the Check links job is failing because the user guide is not in the _index.md. 

> Cannot find: helm-to-operator-codegen-sdk-user-guide.md in content/en/docs/guides/user-guides/helm/_index.md

2024-02-23 10:36 UTC, CsatariGergely requested changes

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +<details>
I would use the `<details>` tag here, It makes the content collapsed by default, so people will just not recognise it. Is this something what is not important?

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +<details>
I think this should be simply just normal description.

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +```
Why is this intro text is added as a code example?

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +#### i) Struct_Module_mapping.json
```suggestion
#### Struct_Module_mapping.json
```

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +#### ii) Enum_Module_mapping.json
```suggestion
#### Enum_Module_mapping.json
```

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +<details>
I would leave the `<details>`

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +```
All of this is normal description and not example code.

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +title: Helm to Operator Codegen Sdk Developer Guide
Is this a document for the developers of Helm to Operator Codegen Sdk?
If yes, then it should be moved to the Nephio contributor guides section.

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +```console
```suggestion
```bash
```

2024-02-23 10:36 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +```
```suggestion
```bash
```

2024-02-26 10:11 UTC, jain-ashish-sam commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +4. A Kubernetes Cluster with Calico CNI and multus-cni plugin (Can Refer [here](https://medium.com/rahasak/deploying-5g-core-network-with-free5gc-kubernets-and-helm-charts-29741cea3922), Before "Depl
Yes, I recall, there were some additional configurations while working with Calico CNI , but thanks for the info about Flannel, I will surely check it out!!

2024-02-26 10:21 UTC, jain-ashish-sam commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +title: Helm to Operator Codegen Sdk Developer Guide
Yes, it is intended for developers, I will surely move it to  "Nephio contributor guides section."

2024-02-26 11:14 UTC, jain-ashish-sam commented
/retest

2024-02-27 08:07 UTC, CsatariGergely commented
> Hi @CsatariGergely , can you help me resolve the "broken-links" issue/ "linkspector job failing". I have checked the links in my own local hugo server, as well as the netlify-preview (https://deploy-preview-117--nephio.netlify.app/). The links seems to work there just fine. I have tried relative-links in one old-commit, but still the job-failed. Therefore, I am not able to get "why the job is failing." The logs of the job don't seem to be much helpful, (https://github.com/nephio-project/docs/actions/runs/8047908663/job/21978126772?pr=117)
> 
> ```
> Run linkspector check -c .linkspector.yml
>   linkspector check -c .linkspector.yml
>   shell: /usr/bin/bash -e {0}
> 💥 Error: Protocol error (Target.closeTarget): Session with given id not found.
> Error: Process completed with exit code 1.
> ```

Hi, I think it is "just" a flaky run. Someone with elevated rights could re-run the failed jobs.
I could run it in my ~~machine~~ fork and it gave more meaningful results: 
![image](https://github.com/nephio-project/docs/assets/11458775/47588eab-62c1-43ac-8a9f-a6118304b485)

2024-02-27 08:24 UTC, CsatariGergely requested changes

2024-02-27 08:24 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +For advanced requirements, Please refer to the developer guide [here](/docs/guides/contributor-guides/helm-to-operator-codegen-sdk-developer-guide.md)
```suggestion
For advanced requirements, Please refer to the developer guide [here](/content/en/docs/guides/contributor-guides/helm-to-operator-codegen-sdk-developer-guide.md)
```

2024-02-27 08:26 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-developer-guide.md
> +<details>
Yes, exactly :)

2024-02-27 08:58 UTC, jain-ashish-sam commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +For advanced requirements, Please refer to the developer guide [here](/docs/guides/contributor-guides/helm-to-operator-codegen-sdk-developer-guide.md)
Thanks!!, The job passed finally!! :)

2024-02-27 08:59 UTC, jain-ashish-sam commented
So, any more comments anyone?

2024-02-29 17:36 UTC, jain-ashish-sam commented
@efiacor @lapentad @CsatariGergely @electrocucaracha @liamfallon @tliron ,If there not further comments, Can we merge this PR?

2024-02-29 18:08 UTC, electrocucaracha commented on content/en/docs/guides/contributor-guides/helm-to-operator-codegen-sdk-developer-guide.md
> +`helm template <chart>  --namespace <namespace>  --output-dir “temp/templated/”` Internally. As of now, it retrieves the values from default "values.yaml"
```suggestion
`helm template <chart>  --namespace <namespace>  --output-dir “temp/templated/”` internally. As of now, it retrieves the values from default "values.yaml"
```

2024-02-29 18:08 UTC, electrocucaracha commented on content/en/docs/guides/user-guides/helm/helm-to-operator-codegen-sdk-user-guide.md
> +## Excercise: Deploying Free5gc using operator
```suggestion
## Exercise: Deploying Free5gc using operator
```

2024-03-01 17:36 UTC, jain-ashish-sam commented
@efiacor @lapentad @CsatariGergely @electrocucaracha @liamfallon @tliron , any further comments?

2024-03-01 18:02 UTC, liamfallon commented
/approve

2024-03-01 19:36 UTC, electrocucaracha commented
/lgtm

2024-03-01 19:37 UTC, merged