Modelling of Nephio API objects
nephio-project/docs pull request #126
Opened 2024-04-17 20:29 UTC by ciaranjohnston

After some reviews in the modelling (WG4) meetings somewhat of a consensus has been reached on a view of the Nephio models, and this is the attempt to describe diagrammatically at a hight level what is currently there.

2024-04-18 06:25 UTC, CsatariGergely requested changes

2024-04-18 07:31 UTC, efiacor commented on content/en/docs/apis/_index.md
> +this page aims to give a high level overview of the objects that are available and their
```suggestion
This page aims to give a high level overview of the objects that are available and their
```

2024-04-18 07:31 UTC, efiacor commented on content/en/docs/apis/_index.md
> +developed ny Tal Liron.
```suggestion
developed by Tal Liron.
```

2024-04-19 10:46 UTC, ciaranjohnston commented on content/en/docs/apis/_index.md
> +## Porch
I think having a recognition that content is needed here is good. I would work on this over the next few days and make a new PR for that

2024-04-19 10:57 UTC, ciaranjohnston commented on content/en/docs/apis/_index.md
> +
I've done that in the latest commit, thanks!

2024-04-19 12:51 UTC, CsatariGergely commented
/approve

2024-05-02 17:59 UTC, liamfallon commented
/approve
/lgtm

2024-05-02 18:00 UTC, merged