Add approved SIG1 user stories
nephio-project/docs pull request #134
Opened 2024-06-10 13:14 UTC by adetalhouet

2024-06-11 07:34 UTC, liamfallon commented on content/en/docs/network-architecture/_index.md
> +SIG1 Network Architecture focuses on defining and developing network architecture identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs an
``
```suggestion
SIG1 Network Architecture focuses on defining and developing network architecture as well as identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs and priorities of stakeholders, such as network administrators, security officers, engineers, and end-users.
```

2024-06-11 07:36 UTC, liamfallon commented on content/en/docs/network-architecture/_index.md
> +This website contains only a subset, approved contant, of the produced materials. Everything is available for anyone's consumption in [Nephio SIG1 Google Drive](https://drive.google.com/drive/u/2/fol
```suggestion
This website contains approved content, which is a subset of the material produced by SIG1. Everything is available for anyone's consumption in [Nephio SIG1 Google Drive](https://drive.google.com/drive/u/2/folders/1P4bmDppUIrtBbiRe3fj92xA_qlCMn7sf).
```

2024-06-11 12:53 UTC, adetalhouet commented on content/en/docs/network-architecture/_index.md
> +SIG1 Network Architecture focuses on defining and developing network architecture identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs an
The point here is to say the network architecture is identifying and/or exercising the Nephio's enablers. The later part of the sentence shouldn't be read as another thing SIG1 is doing. This is done as part of the network architecture.

2024-06-12 12:12 UTC, CsatariGergely requested changes

2024-06-12 12:12 UTC, CsatariGergely commented on content/en/docs/network-architecture/user-stories/Create O-Cloud Node Cluster.md
> +  <iframe class="responsive-iframe" src="https://docs.google.com/presentation/d/e/2PACX-1vTCgOufcrbqNHkopzOVS_yuvcN2H4ZDJc-LEGEiSAhSIUWS0_2h4IZ5GP0Eq0WXqg/embed?start=false&loop=false&delayms=3000" f
We should avoid adding Google docs or wiki pages to the documentation. These do not support proper versioning. 

For me the content of the Google slides looks like a design document. I'm not sure if we should publish design documents in the documentation pages.

2024-06-13 07:45 UTC, liamfallon commented on content/en/docs/network-architecture/_index.md
> +SIG1 Network Architecture focuses on defining and developing network architecture identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs an
Would this read better?

SIG1 Network Architecture focuses on defining and developing network architecture ***by*** identifying and/or exercising Nephio's enablers.

2024-06-27 17:11 UTC, adetalhouet commented on content/en/docs/network-architecture/_index.md
> +SIG1 Network Architecture focuses on defining and developing network architecture identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs an
Fixed

2024-06-27 17:12 UTC, adetalhouet commented on content/en/docs/network-architecture/user-stories/Create O-Cloud Node Cluster.md
> +  <iframe class="responsive-iframe" src="https://docs.google.com/presentation/d/e/2PACX-1vTCgOufcrbqNHkopzOVS_yuvcN2H4ZDJc-LEGEiSAhSIUWS0_2h4IZ5GP0Eq0WXqg/embed?start=false&loop=false&delayms=3000" f
Agreed. We ended up providing documentation for the O-RAN Integration. No longer referencing any gdoc.

2024-06-28 07:31 UTC, liamfallon reviewed
/lgtm
/approve

2024-06-28 07:31 UTC, merged

2024-06-28 11:51 UTC, tcareyintx commented on content/en/docs/network-architecture/O-RAN Integration.md
Is O-RAN Integration.md a correct convention for naming documentation files? seems the convention is lowercase with dashes. So maybe oran-integration.md?

2024-06-28 11:51 UTC, tcareyintx commented on content/en/docs/network-architecture/O-RAN Integration.md
> +-Infrastructure services for the lifecycle management of Cloud Resources (FOCOM, IMS): These services are deployed and utilizes the Nephio capabilities provided by Nephio Management Clusters. In some
This did not get a bullet missing space on the dash.

2024-06-28 11:51 UTC, tcareyintx commented on content/en/docs/network-architecture/_index.md
> +SIG1 Network Architecture focuses on defining and developing network architecture by identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs
spelling excercicing?

2024-06-28 11:51 UTC, tcareyintx commented on content/en/docs/network-architecture/O-RAN Integration.md
> +As stated, the role of the FOCOM function is to provide federated orchestration and management across multiple O-Clouds using the O2ims interface between the O-Clouds as shown in the figure below:
This statement got mixed in with the previous Note. Should be it's own statement.

2024-06-28 11:51 UTC, tcareyintx commented on content/en/docs/network-architecture/O-RAN Integration.md
> +This use case describes the high-level steps and requirements for deployment of O-RAN NF that is composed as discrete NF Deployments across the O2dms using the K8s profile.
This should be a separate paragraph. Markup keeps it with the previous sentence.

2024-06-28 12:27 UTC, liamfallon commented
I see @tcareyintx made some comments after the PR was merged. @adetalhouet if changes are needed based on @tcareyintx comments, I guess we could raise another PR with those changes.

2024-06-28 12:29 UTC, adetalhouet commented on content/en/docs/network-architecture/O-RAN Integration.md
fixed here https://github.com/nephio-project/docs/pull/147

2024-06-28 12:29 UTC, adetalhouet commented on content/en/docs/network-architecture/O-RAN Integration.md
> +-Infrastructure services for the lifecycle management of Cloud Resources (FOCOM, IMS): These services are deployed and utilizes the Nephio capabilities provided by Nephio Management Clusters. In some
fixed here https://github.com/nephio-project/docs/pull/147

2024-06-28 12:29 UTC, adetalhouet commented on content/en/docs/network-architecture/_index.md
> +SIG1 Network Architecture focuses on defining and developing network architecture by identifying and/or exercicing Nephio's enablers. The group's work is guided by user stories that capture the needs
fixed here https://github.com/nephio-project/docs/pull/147

2024-06-28 12:29 UTC, adetalhouet commented on content/en/docs/network-architecture/O-RAN Integration.md
> +As stated, the role of the FOCOM function is to provide federated orchestration and management across multiple O-Clouds using the O2ims interface between the O-Clouds as shown in the figure below:
fixed here https://github.com/nephio-project/docs/pull/147

2024-06-28 12:29 UTC, adetalhouet commented on content/en/docs/network-architecture/O-RAN Integration.md
> +This use case describes the high-level steps and requirements for deployment of O-RAN NF that is composed as discrete NF Deployments across the O2dms using the K8s profile.
fixed here https://github.com/nephio-project/docs/pull/147

2024-06-28 12:30 UTC, adetalhouet commented
@tcareyintx Thanks for the review. Unfortunately the PR was merged to soon. I fixed the outstanding comments here fixed here https://github.com/nephio-project/docs/pull/147