Re-arranging the documentation
nephio-project/docs pull request #148
Opened 2024-06-30 09:38 UTC by arora-sagar

- Added how to create a repo
- Secret for git repo required by Nephio controller

Tested single VM and multiple VM steps.

2024-06-30 09:44 UTC, arora-sagar commented
@vjayaramrh and @dkosteck please check if you are fine with my edit. Instead of using the term **Real K8s** I have changed it to **Other K8s Distributions** because the term real is misleading. Even other **Other K8s Distributions** is not the best choice but I suppose better than real.

2024-07-01 11:30 UTC, liamfallon reviewed
/approve

2024-07-01 12:46 UTC, CsatariGergely requested changes

2024-07-01 12:46 UTC, CsatariGergely commented on content/en/docs/guides/_index.md
> +* [Nephio install guides](/content/en/docs/guides/install-guides/_index_.md): Help in installing Nephio in different environments
```suggestion
* [Nephio install guides](./install-guides/): Help in installing Nephio in different environments
```

2024-07-01 13:24 UTC, vjayaramrh commented on content/en/docs/guides/install-guides/_index.md
> +**Other K8s Distributions**
How about Pre-installed K8S clusters instead of Other K8s Distributions?

2024-07-01 14:21 UTC, arora-sagar commented on content/en/docs/guides/install-guides/_index.md
> +**Other K8s Distributions**
Okay sounds good, I will change it

2024-07-01 14:22 UTC, dkosteck requested changes
Hello @arora-sagar, I have added some suggestions that I think help with readability, some spelling/capitalization, etc. Feel free to disagree with them if you think it reads fine now. I also commented on Vish's response to "Real" clusters, and a clarifying question

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +Get a [GitHub token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#fine-grained-personal-access-tokens) if your repository is pri
I'm confused by the "or allow Porch to make modifications" portion of this step. Perhaps it's me being newer and not understanding, but should there be some clarification here? How would that be done?

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +If need credentials to access repository your repository then
```suggestion
If you need credentials to access your repository then 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +copy the token name from previous section and provide it in
```suggestion
copy the token name from the previous section and provide it in 

```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +Management or workload cluster both need config-sync, root-sync and a cluster git repository to manage packages.
```suggestion
The management or workload cluster both need config-sync, root-sync and a cluster git repository to manage packages. 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +If you are using Gitea then you can use the following steps
```suggestion
If you are using Gitea then you can use the following steps:
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +* In the `repository` package by default Gitea address is `172.18.0.200:3000` in `repository/set-values.yaml`
```suggestion
* In the `repository` package the default Gitea address is `172.18.0.200:3000`. In `repository/set-values.yaml` 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +change this to your Gitea address
```suggestion
change this to your Gitea address.
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +* `repository/token-configsync.yaml` and `repository/token-porch.yaml` are responsible for creating secrets with the help of Nephio token controller for accessing git instance for root-sync. You woul
```suggestion
* `repository/token-configsync.yaml` and `repository/token-porch.yaml` are responsible for creating secrets with the help of the Nephio token controller for accessing the git instance for root-sync. You would need the name of the config-sync token to provide it to root-sync.
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +Change `./rootsync/rootsync.yaml` and point `spec.git.repo` to the edge git repository and the
```suggestion
Change `./rootsync/rootsync.yaml` and point `spec.git.repo` to the edge git repository:
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +If need credentials to access repository your repository then
```suggestion
If need credentials to access your repository then 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +copy the token name from previous section and provide it in
```suggestion
copy the token name from the previous section and provide it in
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +`./rootsync/rootsync.yaml`
```suggestion
`./rootsync/rootsync.yaml`:
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +Deploy the modified root-sync
```suggestion
Deploy the modified root-sync:
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-single-vm.md
> +is similar as below then root-sync is properly configured.
```suggestion
is similar to the following then root-sync is properly configured. 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +is similar as below then root-sync is properly configured.
```suggestion
is similar to the following then root-sync is properly configured. 

```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +If you want to use Github or Gitlab then follow below steps
```suggestion
If you want to use GitHub or GitLab then follow below steps

```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +All the workload clusters need config-sync, root-sync and a cluster git repository to manage packages. Below steps you have to repeat for each workload cluster:
```suggestion
All the workload clusters need config-sync, root-sync and a cluster git repository to manage packages. The below steps have to repeated for each workload cluster:

```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +  * **Ingress/Load Balancer**: [MetalLB](https://metallb.universe.tf/), but only internally to the VM.
```suggestion
  * **Ingress/Load Balancer**: [MetalLB](https://metallb.universe.tf/), but only internally to the VM

```
For consistency in the list

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-byoc.md
> +The R1 and R2 demo environments uses [MetalLB](https://metallb.universe.tf/), but if you are running in a cloud, you
```suggestion
The R1 and R2 demo environments use [MetalLB](https://metallb.universe.tf/), but if you are running in a cloud, you
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/common-dependencies.md
> +You can find gitea ip-address via `kubectl get svc -n gitea`
```suggestion
You can find the Gitea ip-address via `kubectl get svc -n gitea` 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/common-dependencies.md
> +which are getting deployed or already deployed on the cluster. Either you can
```suggestion
which are getting deployed or are already deployed on the cluster. Either you can 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/common-components.md
> +Nephio webui is optional and to install it you can follow this [document](/content/en/docs/guides/install-guides/webui.md)
It is written as "webui" here, but elsewhere as "web-ui". Capitalization is also not consistent I believe, so perhaps standardize this across the changes?

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/common-components.md
> +GitOps tool (ConfigSync) is installed to allow
```suggestion
A GitOps tool (ConfigSync) is installed to allow
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/common-components.md
> +Nephio Operator package by default uses Gitea instance at `172.18.0.200:3000` as
```suggestion
The Nephio Operator package by default uses the Gitea instance at `172.18.0.200:3000` as 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/common-components.md
> +git repository. Change it to point to your git instance in
```suggestion
the git repository. Change it to point to your git instance in  
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/install-guides/_index.md
> +* [Install using vagrant on windows (for development)](/content/en/docs/guides/install-guides/demo-vagrant-windows.md)
```suggestion
* [Install using vagrant on Windows (for development)](/content/en/docs/guides/install-guides/demo-vagrant-windows.md) 
```

2024-07-01 14:22 UTC, dkosteck commented on content/en/docs/guides/_index.md
> +* [Nephio install guides](./install-guides/): Help in installing Nephio in different environments
```suggestion
* [Nephio install guides](./install-guides/): Help in installing Nephio in different environments.
```

2024-07-01 14:25 UTC, arora-sagar commented on content/en/docs/guides/_index.md
> +* [Nephio install guides](./install-guides/): Help in installing Nephio in different environments
Already done

2024-07-01 14:39 UTC, arora-sagar commented on content/en/docs/guides/install-guides/common-components.md
> +Nephio webui is optional and to install it you can follow this [document](/content/en/docs/guides/install-guides/webui.md)
I will change it to WebUI everywhere. As that is how it is written in the webui.md

2024-07-01 14:42 UTC, arora-sagar commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +Get a [GitHub token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#fine-grained-personal-access-tokens) if your repository is pri
I left it how it was earlier, I suppose it should be "to allow Porch to make modifications"

2024-07-01 14:44 UTC, dkosteck commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +Get a [GitHub token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#fine-grained-personal-access-tokens) if your repository is pri
Right, I think that probably makes more sense in this context

2024-07-01 14:51 UTC, dkosteck commented
> > Hello @arora-sagar, I have added some suggestions that I think help with readability, some spelling/capitalization, etc. Feel free to disagree with them if you think it reads fine now. I also commented on Vish's response to "Real" clusters, and a clarifying question
> 
> @dkosteck I have resolved the conversation for the changes you have suggested. Let me know if there is something left.

Looks good. Thanks!

2024-07-01 14:56 UTC, CsatariGergely commented
/approve

2024-07-01 14:56 UTC, arora-sagar commented
@CsatariGergely Can we merge it now?

2024-07-01 14:58 UTC, CsatariGergely commented
Closes: https://github.com/nephio-project/nephio/issues/592

2024-07-01 15:06 UTC, merged

2024-07-01 15:08 UTC, vjayaramrh commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +export ANSIBLE_CMD_EXTRA_VAR_LIST="k8s.context=kind-kind kind.enabled=false host_min_vcpu=4 host_min_cpu_ram=8"
@arora-sagar Is this captured in a the user provided environment varaibles table?

2024-07-01 15:11 UTC, arora-sagar commented on content/en/docs/guides/install-guides/install-on-multiple-vm.md
> +export ANSIBLE_CMD_EXTRA_VAR_LIST="k8s.context=kind-kind kind.enabled=false host_min_vcpu=4 host_min_cpu_ram=8"
@vjayaramrh This was already there I did add it, though I tried to run the script and frankly I failed so I am not sure if it is correct.