Instructions for VM debug setup ofr Porch
nephio-project/docs pull request #158
Opened 2024-07-26 16:27 UTC by liamfallon

See also https://github.com/nephio-project/porch/pull/89

2024-07-27 09:40 UTC, CsatariGergely requested changes

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
We started to use `bash` kind of syntax highlight in these cases. This makes the terminal input and output texts look consitent.

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +```
```suggestion
```bash
```

2024-07-27 09:40 UTC, CsatariGergely commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +You have now set up the VM so that it can be used for remove debugging of Porch.
```suggestion
You have now set up the VM so that it can be used for remote debugging of Porch.
```

I guess

2024-07-27 09:42 UTC, CsatariGergely commented
Gah, I've managed to put a typo to the folder name: 
![image](https://github.com/user-attachments/assets/638a9de7-ae0c-464c-885f-8fb3360d677a)
 I will fix it after this one is merged.

2024-08-07 08:14 UTC, efiacor commented on content/en/docs/porch/contribturos-guide/environment-setup-vm.md
> +## Setting up VSCode
Do we need to mention somewhere to scale down/uninstall the existing porch deployments before running the "local" one?

2024-08-08 06:34 UTC, CsatariGergely commented
/approve

2024-08-08 07:22 UTC, efiacor commented
/approve

2024-08-08 07:22 UTC, efiacor commented
/lgtm

2024-08-08 07:23 UTC, merged