Update o-ran-integration.md
nephio-project/docs pull request #163
Opened 2024-08-09 06:06 UTC by NMSVishal

Added NFO REST API details which are used for OAI NF deployments.

2024-08-15 10:50 UTC, CsatariGergely requested changes

2024-08-15 10:50 UTC, CsatariGergely commented on content/en/docs/network-architecture/o-ran-integration.md
> +##  input will be packagevariant of OAI NF.
I do not think that this should be a H2 heading. If you would like to highlight this just use `*` or `**` around the sentence.

2024-08-15 10:50 UTC, CsatariGergely commented on content/en/docs/network-architecture/o-ran-integration.md
> +##### NFO API For OAI DU NF Deployment:
I would not use a heading here. Maybe a bulleted list is a better option.

2024-08-15 10:50 UTC, CsatariGergely commented on content/en/docs/network-architecture/o-ran-integration.md
> +##### NFO API For OAI CU_CP NF Deployment:
I would not use a heading here. Maybe a bulleted list is a better option.

2024-08-15 10:50 UTC, CsatariGergely commented on content/en/docs/network-architecture/o-ran-integration.md
> +##### NFO API For OAI CU_UP NF Deployment:
I would not use a heading here. Maybe a bulleted list is a better option.

2024-08-21 10:46 UTC, NMSVishal commented on content/en/docs/network-architecture/o-ran-integration.md
> +##### NFO API For OAI CU_UP NF Deployment:
Sure ,I will change it to normal text

2024-08-21 10:51 UTC, NMSVishal reviewed
Removed h2 header format from NFO API Details section as suggested by @CsatariGergely

2024-08-21 10:54 UTC, NMSVishal commented
@CsatariGergely  ,I have modified the

2024-08-21 10:54 UTC, closed without merging