Porch private authenticated registries documentation
nephio-project/docs pull request #178
Opened 2024-10-22 09:11 UTC by Catalin-Stratulat-Ericsson

Paired with PR [#126](https://github.com/nephio-project/porch/pull/126)

This provides documentation on how to configure porch to use external private authenticated registries.

2024-10-22 10:56 UTC, CsatariGergely requested changes

2024-10-22 10:56 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +1. Create a kubernetes secret using a docker `config.json` file.
```suggestion
1. Create a kubernetes secret using a docker *config.json* file.
```
Please use ** for filenames (https://docs.nephio.org/docs/guides/contributor-guides/documentation/#style-guide)

2024-10-22 10:56 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> + A quick way to generate this secret for your use using your docker `config.json` would be to run the following.
```suggestion
 A quick way to generate this secret for your use using your docker *config.json* would be to run the following.
```

2024-10-22 10:56 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +This should generate a secret template similar to the one below which you can add to the `2-function-runner.yaml` file present on the Porch deployment found [here](https://github.com/nephio-project/c
```suggestion
This should generate a secret template similar to the one below which you can add to the *2-function-runner.yaml* file present on the Porch deployment found [here](https://github.com/nephio-project/catalog/tree/main/nephio/core/porch)
```

2024-10-22 10:56 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Next you must mount the secret as a volume on the function runner in the `2-function-runner.yaml` as follows
```suggestion
Next you must mount the secret as a volume on the function runner in the *2-function-runner.yaml* as follows
```

2024-10-22 10:56 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Note the chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. `e.g.` if you wish to mount on
Please use the Hugo note syntax
{{% alert title="Warning" color="primary" %}}
This is a note.
{{% /alert %}}

2024-10-22 10:56 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Note the chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. `e.g.` if you wish to mount on
```suggestion
Note the chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. For example if you wish to mount on `/var/tmp` you should use `mountPath: /var/tmp/<SUB_DIRECTORY>` etc.
```

2024-10-22 11:24 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +1. Create a kubernetes secret using a docker `config.json` file.
changed to use * instead of ` as per the style guide. apologies i didn't see it before this is my first documentation PR :)

2024-10-22 11:24 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> + A quick way to generate this secret for your use using your docker `config.json` would be to run the following.
changed to use * instead of ` as per the style guide

2024-10-22 11:24 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +This should generate a secret template similar to the one below which you can add to the `2-function-runner.yaml` file present on the Porch deployment found [here](https://github.com/nephio-project/c
changed to use * instead of ` as per the style guide

2024-10-22 11:25 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Note the chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. `e.g.` if you wish to mount on
changed the notes to use Hugo syntax.

2024-10-22 11:25 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Note the chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. `e.g.` if you wish to mount on
changed instances of e.g. to For example as per your suggestion.

2024-10-22 11:26 UTC, CsatariGergely requested changes

2024-10-22 11:26 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +{{% alert title="Warning" color="primary" %}}
```suggestion
{{% alert title="Note" color="primary" %}}
```

Aagh sorry, it is a Note, not a Warning.

2024-10-22 11:26 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +{{% alert title="Warning" color="primary" %}}
```suggestion
{{% alert title="Note" color="primary" %}}
```

2024-10-22 11:28 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +{{% alert title="Warning" color="primary" %}}
yes i had a look at the preview there and was wondering why it said warning. ill go make that change now

2024-10-22 11:33 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Next you must mount the secret as a volume on the function runner in the `2-function-runner.yaml` as follows
changed to use * instead of ` as per the style guide

2024-10-22 11:33 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +{{% alert title="Warning" color="primary" %}}
fixed now

2024-10-22 11:33 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +{{% alert title="Warning" color="primary" %}}
fixed also

2024-10-24 15:24 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Lastly you must add the `--registry-auth-secret-path` to the function runner arguments, giving the path of the secret file mount.
Consider "`...to the arguments of the function-runner Deployment object in the *2-function-runner.yaml* file:`, giving the path of the secret file mount:"

2024-10-29 10:07 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +The secret should be in the same namespace as the function runner deployment which by default is the *porch-system* namespace.
amended as per request.

2024-10-29 10:07 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +The secret should be in the same namespace as the function runner deployment which by default is the *porch-system* namespace.
amended as per request.

2024-10-29 10:07 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> + A quick way to generate this secret for your use using your docker *config.json* would be to run the following.
amended as per request.

2024-10-29 10:07 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +title: "Using external private registries"
amended as per request.

2024-10-29 10:08 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +title: "Using external private registries"
and changed the file name to match

2024-10-29 10:08 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +To enable the Porch function runner to communicate with authenticated private registries, we must:
amended as per request.

2024-10-29 10:08 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +The chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. For example if you wish to mount on
amended as per request.

2024-10-29 10:08 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +To enable the Porch function runner to communicate with authenticated private registries, we must:
amended as per request.

2024-10-29 10:08 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +3. Provide this secret mount path to the function runner using the argument `--registry-auth-secret-path`
amended as per request.

2024-10-29 10:08 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +With this last step, if your Porch package uses a custom kpt function image stored in a private registry (For example `- image: ghcr.io/private-registry/set-namespace:customv2`), the function runner
amended as per request.

2024-10-29 10:15 UTC, Catalin-Stratulat-Ericsson commented
/retest

2024-10-29 10:36 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +To enable the Porch function runner to pull kpt function images from authenticated private registries, the system requires the:
Could remove the "the" at the end - then in point 1 below, "Creation of" can be replaced with "Creating" to unify the grammar between the points.

2024-10-29 10:55 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +title: "Using external private registries"
Looks good

2024-10-29 12:24 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +title: "Using external private registries"
Looks good - OK to resolve

2024-10-29 12:24 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +To enable the Porch function runner to communicate with authenticated private registries, we must:
Looks good - OK to resolve

2024-10-29 12:28 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +3. Provide this secret mount path to the function runner using the argument `--registry-auth-secret-path`
Looks good - OK to resolve

2024-10-29 12:28 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> + A quick way to generate this secret for your use using your docker *config.json* would be to run the following.
Looks good - OK to resolve

2024-10-29 12:28 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +The secret should be in the same namespace as the function runner deployment which by default is the *porch-system* namespace.
Looks good - OK to resolve

2024-10-29 12:28 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +The secret should be in the same namespace as the function runner deployment which by default is the *porch-system* namespace.
Looks good - OK to resolve

2024-10-29 12:42 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Lastly you must add the `--registry-auth-secret-path` to the function runner arguments, giving the path of the secret file mount.
Looks good - OK to resolve

2024-10-29 12:42 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +With this last step, if your Porch package uses a custom kpt function image stored in a private registry (For example `- image: ghcr.io/private-registry/set-namespace:customv2`), the function runner
Looks good - OK to resolve

2024-10-29 12:44 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +To enable the Porch function runner to communicate with authenticated private registries, we must:
(another comment on updated version - OK to resolve this one)

2024-10-29 14:55 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +1. Create a kubernetes secret using a docker *config.json* file.
amended as per request.

2024-10-29 15:03 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +1. Create a kubernetes secret using a docker *config.json* file.
Looks good 👍

2024-10-29 15:09 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +This should generate a secret template similar to the one below which you can add to the *2-function-runner.yaml* file present on the Porch deployment found [here](https://github.com/nephio-project/c
Looks good 👍

2024-10-29 15:10 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +Next you must mount the secret as a volume on the function runner in the *2-function-runner.yaml* as follows
Looks good 👍

2024-10-29 15:10 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-external-private-repositories.md
> +The chosen `mountPath:` should use its own directory if placed in an existing directory so that it does not overwrite access permissions of the existing directory. For example if you wish to mount on
Looks good 👍

2024-10-29 15:19 UTC, CsatariGergely requested changes

2024-10-29 15:19 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +An example template of what a docker *config.json* file looks like is as follows below. The base64 encoded value `bXlfdXNlcm5hbWU6bXlfcGFzc3dvcmQ=` of the `auth` key decodes to `my_username:my_passwo
```suggestion
An example template of what a docker *config.json* file looks like is as follows below. The base64 encoded value *bXlfdXNlcm5hbWU6bXlfcGFzc3dvcmQ=* of the *auth* key decodes to *my_username:my_password* which is the format used by the config when authenticating.
```

2024-10-29 15:31 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +An example template of what a docker *config.json* file looks like is as follows below. The base64 encoded value `bXlfdXNlcm5hbWU6bXlfcGFzc3dvcmQ=` of the `auth` key decodes to `my_username:my_passwo
amended as per your request & the styling guide.

2024-10-29 15:33 UTC, JamesMcDermott commented
/approve

2024-10-30 17:21 UTC, arora-sagar commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +
@Catalin-Stratulat-Ericsson Secret generated like this `kubectl create secret docker-registry XXXX --docker-server=https://index.docker.io/v1/ --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>` 

Should also work I suppose? That creates a `.dockerconfigjson` inside secrets.

2024-10-31 11:03 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +
1. So long as the content being put into the secret is in the JSON format and follows the docker config.json schema it should work just fine. 
2. One side note i will say regarding doing it that way is that you would be leaving your password/token in plaintext in the terminal and also in the history of the machine which i don't believe should be encouraged or used as the preferred way to create the secret in the documentation.

2024-11-05 09:38 UTC, arora-sagar commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +
Okay I agree with the second point but we can always remove it from the history using `history -d <line-number>`

2024-11-05 09:39 UTC, arora-sagar commented
/approve

2024-11-05 09:39 UTC, arora-sagar commented
Once --> https://github.com/nephio-project/porch/pull/126 is merged then this PR can be merged

2024-11-05 14:42 UTC, kispaljr commented
> Once --> [nephio-project/porch#126](https://github.com/nephio-project/porch/pull/126) is merged then this PR can be merged

+1

2024-11-06 15:01 UTC, JamesMcDermott reviewed
Another few wording/grammar comments

2024-11-06 15:01 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +With this last step, if your Porch package uses a custom kpt function image stored in an authenticated private registry (for example `- image: ghcr.io/private-registry/set-namespace:customv2`), the f
Maybe 'specify' rather than 'attach'? (also comma after 'pods')
```suggestion
With this last step, if your Porch package uses a custom kpt function image stored in an authenticated private registry (for example `- image: ghcr.io/private-registry/set-namespace:customv2`), the function runner will now use the secret info to replicate your secret on the `porch-fn-system` namespace and specify it as an `imagePullSecret` for the function pods, as documented [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).
```

2024-11-06 15:09 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +With this last step, if your Porch package uses a custom kpt function image stored in an authenticated private registry (for example `- image: ghcr.io/private-registry/set-namespace:customv2`), the f
ah right yes. my apologies there i was thinking of it in the context of volume mounting a secret rather than using it as an `imagePullSecret` when writing that. Amended :)

2024-11-06 15:10 UTC, Catalin-Stratulat-Ericsson commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +Lastly you must add the `--enable-private-registry`, `--registry-auth-secret-path` and `--registry-auth-secret-name` to the arguments of the function-runner Deployment object in the *2-function-runne
yes that is cleaner and clearer, thanks

2024-11-06 15:23 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +Lastly you must add the `--enable-private-registry`, `--registry-auth-secret-path` and `--registry-auth-secret-name` to the arguments of the function-runner Deployment object in the *2-function-runne
Looks good - OK to resolve

2024-11-06 15:23 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +All of the `--enable-private-registry`, `--registry-auth-secret-path` and `--registry-auth-secret-name` arguments have default values of *false*, */var/tmp/auth-secret/.dockerconfigjson* and *auth-se
Looks good - OK to resolve

2024-11-06 15:23 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +With this last step, if your Porch package uses a custom kpt function image stored in an authenticated private registry (for example `- image: ghcr.io/private-registry/set-namespace:customv2`), the f
Cool - OK to resolve

2024-11-07 10:51 UTC, JamesMcDermott commented
/approve

2024-11-07 10:53 UTC, merged