Instructions on Porch Tracing setup added to Porch contributor guide
nephio-project/docs pull request #181
Opened 2024-11-05 15:36 UTC by liamfallon

2024-11-05 15:51 UTC, liamfallon commented
/assign @CsatariGergely @JamesMcDermott @efiacor @Catalin-Stratulat-Ericsson @kushnaidu

2024-11-05 17:01 UTC, JamesMcDermott reviewed
Just a few nitpicky little things...

2024-11-05 17:01 UTC, JamesMcDermott commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +   - name: OTEL
Could de-indent the `name` line a few spaces to align it with the `value` line.
(I suppose we can expect the deployment will have other `env` variables as an example, meaning this comment will be just for aesthetics in this file)

2024-11-05 17:50 UTC, liamfallon commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +kubectl apply -f kubectl apply -f https://raw.githubusercontent.com/nephio-project/porch/refs/heads/main/deployments/tracing/deployment.yaml
done.

2024-11-05 17:51 UTC, liamfallon commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +   - name: OTEL
Done.

2024-11-06 06:48 UTC, CsatariGergely requested changes

2024-11-06 06:48 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +Set the `OTEL` environment variable to point at the Jaeger server
```suggestion
Set the *OTEL* environment variable to point at the Jaeger server
```

2024-11-06 06:48 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +In `.vscode/launch.json`:
```suggestion
In *.vscode/launch.json*:
```

2024-11-06 06:48 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +```
```suggestion
```bash
```

2024-11-06 06:48 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +```
```suggestion
```bash
```

2024-11-06 06:48 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +4. Open the Jaeger UI in your browser at http://localhost:16686
```suggestion
4. Open the Jaeger UI in your browser at *http://localhost:16686*
```

2024-11-06 09:23 UTC, CsatariGergely requested changes
In this way hopefully the text is rendered in aliment with the numbered list of the steps.

2024-11-06 09:23 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +Set the *OTEL* environment variable to point at the Jaeger server
```suggestion
   Set the *OTEL* environment variable to point at the Jaeger server
```

2024-11-06 09:23 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +In *.vscode/launch.json*:
```suggestion
   In *.vscode/launch.json*:
```

2024-11-06 09:23 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/environment-setup.md
> +In a shell:
```suggestion
   In a shell:
```

2024-11-07 11:05 UTC, efiacor commented
/approve
/lgtm

2024-11-07 11:07 UTC, merged