Remove Fucntion CR refs
nephio-project/docs pull request #182
Opened 2024-11-11 11:35 UTC by efiacor

The Function CRD and Repo content tyoe has been removed from Porch. This cleans up any remaining refs.

2024-11-11 11:44 UTC, kushnaidu reviewed
Small typo in the PR title else everything looks good to me.

2024-11-11 11:51 UTC, efiacor commented
/restest

2024-11-11 12:01 UTC, Catalin-Stratulat-Ericsson commented
/approve looks good to me apart from the weird test behavior.

2024-11-11 13:27 UTC, CsatariGergely requested changes

2024-11-11 13:27 UTC, CsatariGergely commented on content/en/docs/porch/contributors-guide/_index.md
>  [VSCode](https://code.visualstudio.com/) works really well for editing and debugging.
```suggestion
[VS Code](https://code.visualstudio.com/) works really well for editing and debugging.
```

2024-11-11 13:28 UTC, CsatariGergely commented
We can ignore the reviewdog job result so far. It is fixed in https://github.com/nephio-project/docs/pull/176 what requires the merger of https://github.com/nephio-project/docs/pull/179

2024-11-11 13:47 UTC, kispaljr commented
/lgtm

2024-11-14 06:42 UTC, liamfallon reviewed
/lgtm
/approve

2024-11-14 06:44 UTC, liamfallon commented
/retest

2024-11-14 18:59 UTC, efiacor commented
/retest

2024-11-21 13:14 UTC, liamfallon commented
/approve
/lgtm

2024-11-21 13:15 UTC, merged