Adding documentation for TLS registries configuration
nephio-project/docs pull request #183
Opened 2024-11-13 10:31 UTC by Catalin-Stratulat-Ericsson

Paired with [PR#139](https://github.com/nephio-project/porch/pull/139)

adds documentation for configuring custom CA certificate integration for private TLS registries

2024-11-13 15:55 UTC, CsatariGergely requested changes

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +4. Creating a kubernetes secret using the TLS information for the registry you wish to use.
```suggestion
4. Creating a Kubernetes secret using the TLS information for the registry you wish to use.
```

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
>  1. Creating a kubernetes secret using a JSON file according to the Docker config schema, containing valid credentials for each authenticated registry.
```suggestion
1. Creating a Kubernetes secret using a JSON file according to the Docker config schema, containing valid credentials for each authenticated registry.
```

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +3. Enabling the external registries feature, providing the path and name of the mounted secret to the function runner using the arguments `--enable-private-registry`, `--registry-auth-secret-path` an
```suggestion
3. Enabling the external registries feature, providing the path and name of the mounted secret to the function runner using the arguments *--enable-private-registry*, *--registry-auth-secret-path* and *--registry-auth-secret-name* respectively.
```

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +6. Enabling the TLS feature and providing the path of the mounted secret to the funtion runner using the arguments `--enable-private-registry` and `--tls-secret-path` respectively.
```suggestion
6. Enabling the TLS feature and providing the path of the mounted secret to the function runner using the arguments *--enable-private-registry* and *--tls-secret-path* respectively.
```

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The `--enable-tls-registry` and `--tls-secret-path` variables are only required if the user has a private TLS registry. they are used to indicate to the function runner that it should try and autenti
```suggestion
The *--enable-tls-registry* and *--tls-secret-path* variables are only required if the user has a private TLS registry. they are used to indicate to the function runner that it should try and authenticate to the registry with TLS transport and should use the TLS certificate information found on the path provided in *--tls-secret-path*.
```

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The `--enable-tls-registry` and `--tls-secret-path` arguments have default values of *false* and */var/tmp/tls-secret/* respectively; however these should be configured by the user and are only neces
```suggestion
The *--enable-tls-registry* and *--tls-secret-path* arguments have default values of *false* and */var/tmp/tls-secret/* respectively; however these should be configured by the user and are only necessary when the user has a private TLS registry.
```

2024-11-13 15:55 UTC, CsatariGergely commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +It is vital that the user has configured the node which the function runner is operating on with the certificate information which is used in the `<TLS_SECRET_NAME>`. If this is not configured correc
```suggestion
It is vital that the user has configured the node which the function runner is operating on with the certificate information which is used in the *<TLS_SECRET_NAME>*. If this is not configured correctly even if the certificate is correct the function runner will be able to pull the image but the krm function pod spun up to run the function will error out with a *x509 certificate signed by unknown authority*.
```

2024-11-13 16:35 UTC, CsatariGergely commented
/approve

2024-11-14 13:11 UTC, JamesMcDermott reviewed
Mostly grammar and English nitpicking - couple of questions I may reiterate on the code PR

2024-11-14 13:11 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The *--enable-tls-registry* and *--tls-secret-path* arguments have default values of *false* and */var/tmp/tls-secret/* respectively; however these should be configured by the user and are only neces
Missing comma. Also wording nitpick - the user won't necessarily "have" (own/possess) the registry they're trying to make their function use.
```suggestion
The *--enable-tls-registry* and *--tls-secret-path* arguments have default values of *false* and */var/tmp/tls-secret/* respectively; however, these should be configured by the user and are only necessary when using a private registry secured with TLS.
```

2024-11-14 13:11 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +It is vital that the user has configured the node which the function runner is operating on with the certificate information which is used in the *<TLS_SECRET_NAME>*. If this is not configured correc
Do we know any documentation we could link to here for configuring the node with certificates? Otherwise, wording nitpicks and breaking the second sentence up a bit:
```suggestion
It is vital that the user has pre-configured the Kubernetes node which the function runner is operating on with the same TLS certificate information as is used in the *<TLS_SECRET_NAME>* secret. If this is not configured correctly, then even if the certificate is correctly configured in the function runner, the kpt function will not run - the function runner will be able to pull the image, but the KRM function pod created to run the function will fail with the error *x509 certificate signed by unknown authority*.
```
(not sure about capitalising "KRM"... is it generally used as a full acronym?)

2024-11-18 12:07 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +Please note sections 4, 5 and 6 are only required if your private registries are set up to use TLS with either self signed or custom/local CA's
Question discussed and content agreed upon - OK to resolve

2024-11-18 12:08 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +3. Enabling the external registries feature, providing the path and name of the mounted secret to the function runner using the arguments *--enable-private-registry*, *--registry-auth-secret-path* an
Looks good - OK to resolve

2024-11-18 12:09 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +4. Creating a Kubernetes secret using the TLS information for the registry you wish to use.
Looks good - OK to resolve

2024-11-18 12:15 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +6. Enabling the TLS feature and providing the path of the mounted secret to the function runner using the arguments *--enable-private-registry* and *--tls-secret-path* respectively.
Looks good - OK to resolve

2024-11-18 12:22 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +Next you must mount the secrets as a volume on the function runner deployment. Add the following snippet to the Deployment object in the *2-function-runner.yaml* file noting that the last entries in
Looks good - OK to resolve

2024-11-18 12:25 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +he *--enable-tls-registry* and *--tls-secret-path* variables are only required if a private registry has TLS enabled. They indicate to the function runner that it should attempt authentication to the
Lost the T at the start of this line
```suggestion
The *--enable-tls-registry* and *--tls-secret-path* variables are only required if a private registry has TLS enabled. They indicate to the function runner that it should attempt authentication to the registry using TLS, and should use the TLS certificate information found on the path provided in *--tls-secret-path*.
```

2024-11-18 12:25 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The *--enable-tls-registry* and *--tls-secret-path* variables are only required if the user has a private TLS registry. they are used to indicate to the function runner that it should try and authent
Looks good. Discussed the question offline - thanks for the explanation of the fallback flow where it tries "provided TLS certificates" -> "default/well-known TLS certificates" -> "last-ditch HTTP"
(OK to resolve)

2024-11-18 12:25 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The *--enable-tls-registry* and *--tls-secret-path* arguments have default values of *false* and */var/tmp/tls-secret/* respectively; however these should be configured by the user and are only neces
Looks good - OK to resolve

2024-11-18 12:29 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +It is vital that the user has configured the node which the function runner is operating on with the certificate information which is used in the *<TLS_SECRET_NAME>*. If this is not configured correc
Looks good - thanks for discussion to resolve the question of documentation - heavily dependent on specific cluster/implementation. OK to resolve.

2024-11-18 12:32 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +5. Mounting the secret containing the registries TLS information to the function runner similarly to step 2.
Looks good - OK to resolve

2024-11-18 12:39 UTC, JamesMcDermott commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +It is important to note that enabling TLS registry functionality makes the function runner attempt connection to the registry provided in the porch file using the mounted tls certificate. if this cer
```suggestion
It is important to note that enabling TLS registry functionality makes the function runner attempt connection to the registry provided in the porch file using the mounted TLS certificate. If this certificate is invalid for the provided registry, it will try again using the Intermediate Certificates stored on the machine for use in TLS with "well-known websites" (e.g. GitHub). If this also fails, it will attempt to connect without TLS: if this last resort fails, it will return an error to the user.
```

2024-11-18 14:22 UTC, JamesMcDermott commented
/approve

2024-11-19 07:47 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
I think it would be better to cover each case in separate sections here, it's difficult to follow when the different configuraiton options are mixed together int he explanation.

2024-11-20 13:32 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The sections below will describe the different configuration options of the function runner pertaining to the image storage location of the kpt functions used by the function runner when rendering of
```suggestion
The Porch function runner pulls kpt function images from registries and uses them for rendering kpt packages in Porch. The function runner is set up by default to fetch kpt function images from public container registries such as [GCR](https://gcr.io/kpt-fn/) and the configuration options described here are not required for such public registries.

This document describes a number of options that are available for configuring authentication of private registries for the Porch function runner.  
```

2024-11-20 13:33 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +The sections below will describe the different configuration options of the function runner pertaining to the image storage location of the kpt functions used by the function runner when rendering of
```suggestion
The Porch function runner pulls kpt function images from registries and uses them for rendering kpt packages in Porch. The function runner is set up by default to fetch kpt function images from public container registries such as [GCR](https://gcr.io/kpt-fn/) and the configuration options described here are not required for such public registries.
```

2024-11-20 13:34 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +Please note the function runner is setup to run by default with a public container registry such as [GCR](https://gcr.io/kpt-fn/). No further configuration is required if that is the intended use cas
```suggestion
```

2024-11-20 13:34 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +However if a more customized setup is required please see the below configuration options
```suggestion
```

2024-11-20 13:36 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +If you wish to have a private container registry to store your kpt functions either online e.g. (Github's GHCR) or locally e.g. (Harbor or Jfrog) requiring authentication (username/password or token)
```suggestion
This section describes how set up authentication for a private container registry storing kpt functions online e.g. (Github's GHCR) or locally e.g. (Harbor or Jfrog) that require authentication (username/password or token).
```

2024-11-20 13:37 UTC, liamfallon commented on content/en/docs/porch/using-porch/using-authenticated-private-registries.md
> +To enable the Porch function runner to pull kpt function images from authenticated private registries, the system requires:
```suggestion
To enable pulling of kpt function images from authenticated private registries by the Porch function runner the system requires:
```

2024-11-20 14:41 UTC, liamfallon reviewed
/approve

2024-11-21 10:52 UTC, kushnaidu commented
Looks good Catalin.
/approve

2024-11-25 07:27 UTC, liamfallon commented
/approve
/lgtm

2024-11-25 07:29 UTC, merged