Explore sandbox
nephio-project/docs pull request #24
Opened 2023-06-20 12:52 UTC by liamfallon

2023-06-20 12:53 UTC, liamfallon commented
/assign @electrocucaracha @efiacor @lapentad @henderiw

2023-06-20 13:00 UTC, lapentad reviewed
Is the .drawio file supposed to be there?

2023-06-20 13:02 UTC, liamfallon commented
@lapentad yes, it's the draw.io source file that the .png was generated from. It's there so that the diagram can be modified later.

2023-06-20 16:53 UTC, electrocucaracha requested changes
Great work @liamfallon, thanks for capturing and describing the process. I just found a typo, besides that everything looks good.

2023-06-20 16:53 UTC, electrocucaracha commented on install-guide/ExploreSandbox.md
> +sudo kpt live status /tmp/kpt-pkg/nephio-controllers/
[This PR](https://github.com/nephio-project/test-infra/pull/105) will allow running things without `sudo`
```suggestion
kpt live status /tmp/kpt-pkg/nephio-controllers/
```

2023-06-20 16:53 UTC, electrocucaracha commented on install-guide/ExploreSandbox.md
> +| VLAM         | A system used to allocate and manage VLANs                         |
```suggestion
| VLAN         | A system used to allocate and manage VLANs                         |
```

2023-06-20 20:51 UTC, efiacor approved these changes
Minor suggested edit. Overall looks very helpful.

2023-06-20 20:51 UTC, efiacor commented on install-guide/ExploreSandbox.md
> +$ kubectl get pods -A
Slight improvement if you don't need the kube-system pods

kubectl get pods -A --field-selector=metadata.namespace!=kube-system

2023-06-21 08:46 UTC, liamfallon commented on install-guide/ExploreSandbox.md
> +sudo kpt live status /tmp/kpt-pkg/nephio-controllers/
Done

2023-06-21 08:47 UTC, liamfallon commented on install-guide/ExploreSandbox.md
> +| VLAM         | A system used to allocate and manage VLANs                         |
Done

2023-06-21 08:47 UTC, liamfallon commented on install-guide/ExploreSandbox.md
> +$ kubectl get pods -A
Done

2023-06-21 08:51 UTC, lapentad commented on learning.md
> +* [https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator](https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator): An improved f5ee5gc operator from Orange
```suggestion
* [https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator](https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator): An improved free5gc operator from Orange
```

2023-06-21 09:22 UTC, liamfallon commented on learning.md
> +* [https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator](https://github.com/matysiaq/nephio-pocs/tree/main/free5gc-operator): An improved f5ee5gc operator from Orange
Done

2023-06-22 11:22 UTC, gvbalaji reviewed
Thanks @liamfallon for the nice write up. Added couple of comments.

2023-06-22 11:22 UTC, gvbalaji commented on install-guide/ExploreSandbox.md
> +| IPAM         | A system used to allocate and manage IP addresses                  |
IPAM and VLAN backends are more like reference implementations that we use. In real world customers may use something else.

2023-06-22 12:28 UTC, liamfallon commented on install-guide/ExploreSandbox.md
> +The following base components are installed on the kind management cluster. Base components are standard components in the k8s ecosystem, which Nephio uses out of the box.
@gvbalaji I reworded the document along the lines you suggested.

2023-06-22 12:29 UTC, liamfallon commented on install-guide/ExploreSandbox.md
> +| IPAM         | A system used to allocate and manage IP addresses                  |
I updated this as well.

2023-06-23 09:11 UTC, liamfallon commented
Could we nudge this on please?

2023-06-23 11:48 UTC, henderiw commented
/lgtm
/approve

2023-06-23 11:49 UTC, merged