Add vertical scaling of UPF to exercises
nephio-project/docs pull request #60
Opened 2023-08-30 12:57 UTC by MA3CIN

Work in progress - tomorrow i'll add SMF scaling and pictures from the Web UI for both NFs.

2023-08-30 17:59 UTC, johnbelamaric requested changes

2023-08-30 17:59 UTC, johnbelamaric commented on user-guide/exercises.md
> +package. We can edit this value manually, or use the web interface. Both options result in
s/manually/with the CLI/ (here and in the next line).

the sentence just ends, with "result in", it needs to be finished.

Throughout the doc, change the use of "we" to "you", that's the K8s style for docs we have adopted (I always use "we" as well, then have to change my docs...).

2023-08-30 17:59 UTC, johnbelamaric commented on user-guide/exercises.md
> +To create a new package revision, we need to start by retrieving the package Variant downstream target name.
s/package Variant/PackageVariant/

2023-08-30 17:59 UTC, johnbelamaric commented on user-guide/exercises.md
> +This way we retrieve the downstream target name of the package. You can also retrieve this information by using the `kubectl describe` command on the UPF packageVariant.
s/packageVariant/PackageVariant/

2023-08-30 17:59 UTC, johnbelamaric commented on user-guide/exercises.md
> +new_capacity_value=10
i would probably just put "10" in the commands lines below, instead of using a variable

2023-08-30 17:59 UTC, johnbelamaric commented on user-guide/exercises.md
> +We can check the current lifecycle stage of a package using the `kpt alpha rpkg get`` command.
extra ` here after "get"

2023-08-30 17:59 UTC, johnbelamaric commented on user-guide/exercises.md
> +```
Use "```bash" for ones with commands, and "```console" for the output, throughout the doc.

2023-08-31 11:14 UTC, MA3CIN commented
Adjusted the PR to suggested changes

2023-08-31 18:18 UTC, johnbelamaric requested changes
Very nice. You need to make sure there is a blank line before all the code blocks, but otherwise this looks great.

2023-08-31 18:18 UTC, johnbelamaric commented on user-guide/exercises.md
> +```console
You need a blank line before the three backticks, or it doesn't render correctly:

![image](https://github.com/nephio-project/docs/assets/9468083/c7e4cc59-c6a2-4e95-9e7a-11c302b2809a)

2023-09-03 13:36 UTC, MA3CIN commented
@johnbelamaric seeing as the SMF can also be scaled vertically using the UI, i'd suggest this this PR be merged with UPF only - scaling the amount of sessions/connections the SMF handles has less "fireworks". If the SMF instructions are needed then I can finish it in the meantime in a separate PR - the Observability topic (agents/watchers/status aggregators) is more important for now

2023-09-05 18:55 UTC, electrocucaracha approved these changes
/lgtm 

@johnbelamaric I think that eventually we have to separate this guide in different documents using different interfaces `kubectl`, `kpt` and `WebUI`

2023-09-05 19:05 UTC, johnbelamaric commented
/approve

2023-09-05 19:06 UTC, merged