Adding prelim helm integration guide
nephio-project/docs pull request #66
Opened 2023-09-20 18:31 UTC by efiacor

Adding a placeholder for helm int docs and including a basic readme howto guide on using the existing flux kpt packages.
Also, some refactoring on the structure of the the docs repo.

2023-09-20 18:32 UTC, efiacor commented
@liamfallon

2023-09-20 18:37 UTC, efiacor commented
/cc @liamfallon

2023-09-20 18:38 UTC, efiacor commented
/cc @lapentad

2023-09-20 18:38 UTC, efiacor commented
/cc @tliron

2023-09-20 18:38 UTC, efiacor commented
/cc @s3wong

2023-09-20 18:38 UTC, efiacor commented
/cc @byungwoojun

2023-09-22 09:55 UTC, liamfallon commented
/approve

2023-09-22 17:41 UTC, johnbelamaric requested changes
A few minor tweaks, and I haven't tried it, but looks good generally.

2023-09-22 17:41 UTC, johnbelamaric commented on user-guide/docs/helm/README.md
> +and will progress over the coming releases.\
Extraneous backslash

2023-09-22 17:41 UTC, johnbelamaric commented on user-guide/docs/helm/README.md
> +[Using Flux CD to deploy helm charts in Nephio](https://github.com/nephio-project/docs/blob/main/install-guide/docs/helm/flux-helm.md)
Make this a bulleted list, and then add the other options under consideration (even though they will not have links). At the very least add the Operator SDK and a link to that.

I would also change the link text to just "Using Flux CD".

2023-09-22 17:41 UTC, johnbelamaric commented on user-guide/docs/helm/flux-helm.md
> +[Flux CD](https://fluxcd.io/flux/use-cases/helm/) provides a set of kubernetes controllers to enable a GitOps driven deployment of helm charts, using relevant the flux Custom Resources.
s/kubernetes/Kubernetes/

I would just end the sentence where the comma is.

2023-09-22 20:27 UTC, efiacor commented on user-guide/docs/helm/flux-helm.md
> +[Flux CD](https://fluxcd.io/flux/use-cases/helm/) provides a set of kubernetes controllers to enable a GitOps driven deployment of helm charts, using relevant the flux Custom Resources.
Done

2023-09-22 20:27 UTC, efiacor commented on user-guide/docs/helm/README.md
> +[Using Flux CD to deploy helm charts in Nephio](https://github.com/nephio-project/docs/blob/main/install-guide/docs/helm/flux-helm.md)
Done

2023-09-22 20:27 UTC, efiacor commented on user-guide/docs/helm/README.md
> +and will progress over the coming releases.\
Removed

2023-09-22 20:47 UTC, johnbelamaric approved these changes
/approve
/lgtm

2023-09-22 20:47 UTC, merged