Initial draft for R2 release notes
nephio-project/docs pull request #84
Opened 2024-01-18 00:41 UTC by gvbalaji

We need to augment the contents for install , limitations and troubleshooting sections

2024-01-18 02:05 UTC, electrocucaracha commented on content/en/docs/release-notes/R2.md
> +Please refer to the [Install Guide](https://github.com/nephio-project/docs/tree/main/content/en/docs/guides/install-guides)
I think that it's better to refer to the [BYOC installation document](https://github.com/nephio-project/docs/blob/main/content/en/docs/guides/install-guides/install-on-byoc.md)

2024-01-18 02:05 UTC, electrocucaracha commented on content/en/docs/release-notes/R2.md
> +- Ubuntu-20.04-focal Linux
That restriction is for free5Gc workloads, OAI has been tested on Ubuntu Jammy

2024-01-18 02:05 UTC, electrocucaracha commented on content/en/docs/release-notes/R2.md
> + new web based documentation
```suggestion
  * new web based documentation 
```

2024-01-19 08:18 UTC, CsatariGergely requested changes

2024-01-19 08:18 UTC, CsatariGergely commented on content/en/docs/release-notes/R2.md
> +Please refer to the [Install Guide](https://github.com/nephio-project/docs/tree/main/content/en/docs/guides/install-guides)
Please use `ref` style references instead of referring to the folders of files in GitHub directly.
I've updated this to use the `ref` style reference and to refer to the prerequisites of the BYOC install guide. 

```suggestion
Please refer to the [Install Guide]({{< ref "docs/guides/install-guides/install-on-byoc.md#prerequisites" >}}) for the
prerequisites on supported environments.
```

2024-01-23 19:37 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> +- Ubuntu-20.04-focal Linux
thanks @electrocucaracha . So users need different environments for Free5gc and OAI?

2024-01-23 20:13 UTC, electrocucaracha commented on content/en/docs/release-notes/R2.md
> +- Ubuntu-20.04-focal Linux
Maybe they can use the same, but we have tested with different distros

2024-01-24 01:16 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> +- Ubuntu-20.04-focal Linux
Can you please mention the exact versions here?

2024-01-24 01:17 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> +Please refer to the [Install Guide](https://github.com/nephio-project/docs/tree/main/content/en/docs/guides/install-guides)
Done

2024-01-25 15:08 UTC, arora-sagar commented on content/en/docs/release-notes/R2.md
> +  * Deploying many OAI 5G core and RAN components (CU and DU) NFs via Python-based operators
- Deploying OAI 5G Core and RAN Network Functions (CU-CP, CU-UP, RF Simulated DU)
- OAI 5G Core network functions are developed using Python KOPF (Kubernetes Operator Framework)
- End to End call with RF Simulated OAI-NR-UE

2024-01-25 15:47 UTC, arora-sagar commented on content/en/docs/release-notes/R2.md
> +- Ubuntu-20.04-focal Linux
@gvbalaji Where are we mentioning about Fedora? Because R1 was working in fedora right?

2024-01-30 23:38 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> +  * Deploying many OAI 5G core and RAN components (CU and DU) NFs via Python-based operators
Thanks Done.

2024-01-30 23:38 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> +Please refer to the [Install Guide](https://github.com/nephio-project/docs/tree/main/content/en/docs/guides/install-guides)
Done. Thanks.

2024-01-30 23:38 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> + new web based documentation
Done. Thanks.

2024-01-30 23:38 UTC, gvbalaji commented on content/en/docs/release-notes/R2.md
> +- Ubuntu-20.04-focal Linux
Added, thanks.

2024-01-31 06:47 UTC, CsatariGergely commented
Broken links are fixed in https://github.com/nephio-project/docs/pull/90

2024-01-31 17:35 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* When deploying the sandbox environment on an Ubuntu VM running on OpenStack,
Remove this (or find out what it is about). Ask Francesco?

2024-01-31 17:38 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* Occasionally packages may take a long time to be approved by the auto-approval
Open an issue (epic?) for this.

2024-01-31 17:39 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* Occasional calls to `kpt alpha rpkg copy` may fail with a message like
Open an issue. Change to `porchctl` instead of `kpt alpha`.

2024-01-31 17:39 UTC, electrocucaracha commented on content/en/docs/release-notes/R2.md
> +* When deploying the sandbox environment on an Ubuntu VM running on OpenStack,
@lapentad I know that you were playing around OpenStack, have you ever faced this issue. The way that I fixed in test-infra was adding [these lines](https://github.com/nephio-project/test-infra/pull/230/commits/d12b233aafe4496f05545d8516d29c7b3b82be4c), but I'm not sure if this is the same issue.

2024-01-31 17:45 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +## Known Issues and Workarounds
Add these:

* During specialization we may have duplicate paramaterRef extensions, leading to failed deployments (wrong configurations are generated). The current workaround is to redeploy the package. The bug is due to NFDeploy reconciliation not being correctly idempotent.

* The free5GC operator may create duplicate entries in the SMF function configuration. This is harmless, but still incorrect.

2024-01-31 17:48 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* Integration with new release of Porch
Note that Porch is now part of Nephio, owned by Nephio.

2024-01-31 17:49 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +Please refer to the [Install Guide]({{< ref "docs/guides/install-guides/install-on-byoc.md#prerequisites" >}})
This is a Hugo ref, it won't show in github.com.

2024-01-31 17:51 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +The sandbox environment requires a physical or virtual machine with:
This is for end to end RAN use case only.

2024-01-31 17:52 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +For non-sandbox installations, any conforming Kubernetes cluster is sufficient
Reword:

Note: A Nephio sandbox can be created on any Kubernetes cluster.

2024-01-31 17:53 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* Packages for the dependent services
Typo

2024-01-31 17:53 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* Multi-vendor suppor
support

2024-01-31 17:54 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +  * Experimental: Topology Controller - Northbound API to express the network topology
Remove "experimental"

2024-01-31 17:54 UTC, tliron commented on content/en/docs/release-notes/R2.md
> +* Fixing the Multus version
Upgrading

2024-01-31 23:51 UTC, tliron commented
/lgtm

2024-02-01 00:20 UTC, electrocucaracha commented on content/en/docs/release-notes/R2.md
> +A Nephio sandbox can be created on any Kubernetes cluster.
I'm not sure if we should reduce the scope of this statement. Our [End-to-End tests](https://github.com/nephio-project/test-infra/blob/main/e2e/provision/playbooks/roles/bootstrap/defaults/main.yml#L23) have been performed in `v1.27.1`.
```suggestion
A Nephio sandbox can be created on any [Certified Kubernetes](https://www.cncf.io/training/certification/software-conformance/) v1.27+ cluster.
```

2024-02-01 00:28 UTC, electrocucaracha commented
/lgtm

2024-02-01 00:42 UTC, efiacor commented
/approve
/lgtm

2024-02-01 00:42 UTC, merged