Updating docs for R2
nephio-project/docs pull request #85
Opened 2024-01-18 15:08 UTC by arora-sagar

Updating documentation for release 2

- Installation guide for GCE
- Exercises for OAI and Free5GC

2024-01-25 07:55 UTC, CsatariGergely requested changes

2024-01-25 07:55 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/exercise-1-free5gc.md
This file is referred in the following places: 
* docs/guides/install-guides/install-on-gce.md:176
* docs/guides/user-guides/helm/flux-helm.md:21
* docs/guides/user-guides/helm/flux-helm.md:23
* docs/guides/install-guides/install-on-gcp.md:1387
Please update the file name or remove the references. 
I've created a pr to your pr with my suggestions here: https://github.com/arora-sagar/nephio-docs/pull/1

2024-01-25 07:55 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/exercise-1-free5gc.md
Please add a short description about what is this page. It is rendered to the bottom of the User Guides page: 
![image](https://github.com/nephio-project/docs/assets/11458775/1bd01441-9c85-4557-a388-a786ffc4053f)

2024-01-25 07:55 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +title: Free5GC Testbed Deployment and E2E testing with UERANSIM
I think this title is just a copy paste error.

2024-01-25 07:55 UTC, CsatariGergely commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +
Please add a short description

2024-01-25 07:57 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +title: Free5GC Testbed Deployment and E2E testing with UERANSIM
Yes it is copy paste error, I haven't finished the docs yet. I will do another commit today

2024-01-25 23:17 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-1-free5gc.md
@CsatariGergely I would need @lapentad or @efiacor to tell me for the helm part. I let that broken intentionally.

2024-01-26 08:07 UTC, CsatariGergely approved these changes

2024-01-26 09:30 UTC, efiacor reviewed
Hi @arora-sagar,
Looks good. My only concern is that there is a lot or duplication here. The main diff I see is the cluster provisioning and the nf deploy. I think the main purpose of the orig guide was to show the diff ways to deploy a pkg. ie kpt vs PV/PVS vs UI. I think we should keep that common to both use cases. Maybe in a separate section/file?

2024-01-26 09:44 UTC, arora-sagar commented
> Hi @arora-sagar, Looks good. My only concern is that there is a lot or duplication here. The main diff I see is the cluster provisioning and the nf deploy. I think the main purpose of the orig guide was to show the diff ways to deploy a pkg. ie kpt vs PV/PVS vs UI. I think we should keep that common to both use cases. Maybe in a separate section/file?

@efiacor I don't really get it how you want to do that?

2024-01-26 10:16 UTC, efiacor commented
> > Hi @arora-sagar, Looks good. My only concern is that there is a lot or duplication here. The main diff I see is the cluster provisioning and the nf deploy. I think the main purpose of the orig guide was to show the diff ways to deploy a pkg. ie kpt vs PV/PVS vs UI. I think we should keep that common to both use cases. Maybe in a separate section/file?
> 
> @efiacor I don't really get it how you want to do that?

We prob should break some of the exercise steps into their own sections/files and reuse them. Say for instance the "inter-cluster networking" is common to both.

2024-01-26 10:18 UTC, efiacor commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +[[_TOC_]]
Needs to be defined.

2024-01-26 10:18 UTC, efiacor commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +Be sure you have followed the [installation guide]({{< ref "docs/guides/install-guides ">}})
Make sure to render/preview the links etc

2024-01-26 10:18 UTC, efiacor commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +## Step 4: Deploy Dependencies, MySQL database, OAI Core and RAN Operator in the Workload clusters
I think we are missing a Step 2

2024-01-26 11:14 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +[[_TOC_]]
Yes I will define that I thought it will make it like gitlab, but no.

2024-01-26 11:16 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +Be sure you have followed the [installation guide]({{< ref "docs/guides/install-guides ">}})
About the links I am not sure it is like this in the current exercise.md in `main` too. @CsatariGergely is it suppose to be like this?

2024-01-26 11:16 UTC, arora-sagar commented on content/en/docs/guides/user-guides/exercise-2-oai.md
> +## Step 4: Deploy Dependencies, MySQL database, OAI Core and RAN Operator in the Workload clusters
I will correct

2024-01-26 11:19 UTC, arora-sagar commented
> > > Hi @arora-sagar, Looks good. My only concern is that there is a lot or duplication here. The main diff I see is the cluster provisioning and the nf deploy. I think the main purpose of the orig guide was to show the diff ways to deploy a pkg. ie kpt vs PV/PVS vs UI. I think we should keep that common to both use cases. Maybe in a separate section/file?
> > 
> > 
> > @efiacor I don't really get it how you want to do that?
> 
> We prob should break some of the exercise steps into their own sections/files and reuse them. Say for instance the "inter-cluster networking" is common to both.

@efiacor Actually that section is not common either. Making the workload cluster in both of them is different the topology is different and the networking is also different. 

Both exercises don't share the network, [network topology](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/oai/clab-topo.gotmpl) right now is in dedicated sub-folders. That is the reason I am using the export commands to use the right path.

2024-01-26 11:33 UTC, efiacor commented
> > > > Hi @arora-sagar, Looks good. My only concern is that there is a lot or duplication here. The main diff I see is the cluster provisioning and the nf deploy. I think the main purpose of the orig guide was to show the diff ways to deploy a pkg. ie kpt vs PV/PVS vs UI. I think we should keep that common to both use cases. Maybe in a separate section/file?
> > > 
> > > 
> > > @efiacor I don't really get it how you want to do that?
> > 
> > 
> > We prob should break some of the exercise steps into their own sections/files and reuse them. Say for instance the "inter-cluster networking" is common to both.
> 
> @efiacor Actually that section is not common either. Making the workload cluster in both of them is different the topology is different and the networking is also different.
> 
> Both exercises don't share the network, [network topology](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/oai/clab-topo.gotmpl) right now is in dedicated sub-folders. That is the reason I am using the export commands to use the right path.

Ye maybe not the best example as the networking is all a bit hacky. But say for instance, these files are identical - https://github.com/nephio-project/test-infra/blob/main/e2e/tests/free5gc/clab-topo.gotmpl
https://github.com/nephio-project/test-infra/blob/main/e2e/tests/oai/clab-topo.gotmpl

We may need to revisit this later. I'll ignore the duplication for now.. :smile:

2024-01-29 12:46 UTC, liamfallon commented on content/en/docs/guides/install-guides/install-on-gce.md
> +                                    --metadata=startup-script-url=https://raw.githubusercontent.com/nephio-project/test-infra/v2.0.0/e2e/provision/init.sh,nephio-test-infra-branch=v2.0.0 \
This URL:
https://raw.githubusercontent.com/nephio-project/test-infra/v2.0.0/e2e/provision/init.sh

returns 404 for me.

2024-01-29 12:47 UTC, liamfallon commented on content/en/docs/guides/install-guides/install-on-gce.md
> +wget -O - https://raw.githubusercontent.com/nephio-project/test-infra/v2.0.0/e2e/provision/init.sh |  \
Also this one

2024-01-29 12:52 UTC, liamfallon commented
@arora-sagar Cna you just check the links, it could be something with my setup that they are not working as I'm not using GCE so I'm just checking the links on my local machine.

2024-01-29 13:01 UTC, arora-sagar commented on content/en/docs/guides/install-guides/install-on-gce.md
> +wget -O - https://raw.githubusercontent.com/nephio-project/test-infra/v2.0.0/e2e/provision/init.sh |  \
So the issue here is v2.0.0 tag doesn't exist. The documentation is released before the tag is released.

2024-01-29 13:02 UTC, arora-sagar commented
The tag v2.0.0 tag mentioned in the document doesn't exist for the moment. The documentation is released before the tag is released.

2024-01-29 13:02 UTC, liamfallon commented
/lgtm
/approve

2024-01-29 13:02 UTC, merged