Common dependencies
nephio-project/docs pull request #88
Opened 2024-01-24 12:27 UTC by liamfallon

Update URLs for KPT packages to point at catalog packages and replaced the tag with `@main`, added a note to instruct people to replace the `@main`tag with whatever tag they want to pull

2024-01-24 12:28 UTC, liamfallon commented
/assign @tliron @electrocucaracha @lapentad

2024-01-24 12:31 UTC, efiacor commented
/lgtm

2024-01-24 15:11 UTC, CsatariGergely approved these changes

2024-01-24 16:53 UTC, electrocucaracha commented
/lgtm

2024-01-26 15:31 UTC, efiacor requested changes

2024-01-26 15:31 UTC, efiacor commented on content/en/docs/guides/install-guides/common-components.md
> +kpt pkg get --for-deployment https://github.com/nephio-project/catalog/nephio/core/proch@main
```suggestion
kpt pkg get --for-deployment https://github.com/nephio-project/catalog/nephio/core/porch@main
```

2024-01-31 09:33 UTC, lapentad commented
/approve

2024-01-31 17:04 UTC, efiacor commented
/approve
/lgtm

2024-01-31 17:04 UTC, merged